# -*- coding: utf-8 -*-
"""streamlit

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WGVtL80nv2HEQG3zLBaUg_78X29D8syH
"""

import streamlit as st
import tensorflow as tf

@st.cache_resource
def load_model():
  model=tf.keras.models.load_model('final3.h5')
  return model
model=load_model()
st.write("""
# Cifar10 prediction"""
)
file=st.file_uploader("Choose plant photo from computer",type=["jpg","png"])
import cv2
from PIL import Image,ImageOps
import numpy as np
def import_and_predict(image_data,model):
    size=(64,64)
    image=ImageOps.fit(image_data,size,Image.ANTIALIAS)
    img=np.asarray(image)
    img_reshape=img[np.newaxis,...]
    prediction=model.predict(img_reshape)
    return prediction
if file is None:
    st.text("Please upload an image file")
else:
    image=Image.open(file)
    st.image(image,use_column_width=True)
    prediction=import_and_predict(image,model)
    class_names = ['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']
    string="OUTPUT : "+class_names[np.argmax(prediction)]
    st.success(string)